import { FormBuilderOptionInterface } from "../types";

export const LoginForm: FormBuilderOptionInterface = {
  email: {
    inputType: "email",
    label: "Email",
    labelPlacement: "inside",
    placeholder: "Enter Your email address",
    isRequired: true,
    isClearable: true,
    isDisabled: false,
    isReadOnly: false,
    size: "sm",
    color: "default",
    variant: "faded",
    radius: "sm",
    startContent: undefined,
    endContent: undefined,
    description: "",
    errorMessage: "",
  },
  password: {
    inputType: "password",
    label: "Password",
    labelPlacement: "inside",
    placeholder: "Enter Your secret password",
    isRequired: true,
    isClearable: false,
    isDisabled: false,
    isReadOnly: false,
    size: "sm",
    color: "default",
    variant: "faded",
    radius: "sm",
    startContent: undefined,
    endContent: undefined,
    description: "",
    errorMessage: "",
  },
};
